### ISSUE TITLE
how to produce an Android version?

### ISSUE THREAD

**Issue by axd1967** [ZeusWPI/hydra#218]
Hello,

Could you detail how a (Debug) Android version can be produced? I'm trying to import in AS (1.4.1), but get errors in e.g. `uk.co.senab.actionbarpulltorefresh.library.PullToRefreshAttacher`.

Can you confirm the development environment that is needed?

thx

-alex-

**Comment by Silox** [comment]
Hi Alex,

The Android version was developed in Netbeans, so we only have a [netbeans guide available at our wiki](https://github.com/ZeusWPI/hydra/wiki/Android:-Setup-guide-for-Netbeans-&-Eclipse#netbeans).

If you wish to import the project in AS, you'll have to include the libraries mentioned in the guide linked above in Gradle.

Good luck!

Tom

**Comment by axd1967** [comment]
ok. I totally missed the extensive wiki.

can you rename the Netbeans guide wiki page? the '&' prevents cloning the wiki on Windoze. thx

**Comment by axd1967** [comment]
I intend to focus on this in the coming weeks, but I wondered if there are known issues when attempting to port to Android Studio, that brought you to move to the other hydra variants, or is it just a matter of convenience (and maybe just to start over from a clean slate, or even fork for other reasons)? I'd prefer not to discover issues that may have lead to stop support for AS, and having to find out that it is not really feasible to have an AS version.

thx.

**Comment by Silox** [comment]
Hi Alex,

We never stopped supporting AS, AS just wasn't there when this application
was made and there hasn't been any development since AS was released in a
stable version.

It however is important to notice that we're starting over with a new
implementation in ZeusWPI/hydra-android. We chose to start over with a
clean slate as the Android API and libraries have changed a lot since this
version and the general code quality wasn't very good. The version in the
hydra-android repository is implemented in AS and should import in AS
without any problems.

I'm also not sure what you mean by "other hydra variants", did you mean to
write IDEs instead of hydra?

Tom

2015-12-02 9:11 GMT+01:00 alex <notifications@github.com>:

**Comment by axd1967** [comment]
(I meant the ones you are indeed mentioning:https://github.com/ZeusWPI/hydra-android )

My idea was to submit a small improvement to the existing, *published* Hydra version (assuming the hydra-android version is not ready for release in the coming months): the possibility to invoke a Hydra Intent that opens Hydra straight into the resto menu page, and maybe later, should StJansVest somehow be added, to be able to specify via an Intent extra which resto page should be shown.

**Comment by nielsdg** [comment]
With our UI revamp the resto menu would get a more prominent place in the home page. Committing to this repo is discouraged, as we want to focus our attention to the new hydra-android repo.

**Comment by axd1967** [comment]
For those interested, I forked Hydra v1.1.0 [here](https://github.com/axd1967/Hydra-old-AS)

When I find some time, I intend to expand the current Hydra wiki with how to produce an AS version (knowing that a new version is underway, nevertheless.)

rgds

**Comment by Silox** [comment]
Cool! Looking forward to the instructions, they will probably be of use for the new version too.
