### ISSUE TITLE
Major inconsistencies in DSA API

### ISSUE THREAD

**Issue by nielsdg** [ZeusWPI/hydra#224]
The format for associations seems to be picked at random and is at the brink of being unusable in this state, as it prevents activities from being linked to their respective associations in any way.

Some issues:
* [all_activities.json](http://student.ugent.be/hydra/api/1.0/all_activities.json) uses `internal_name`, while [associations.json](http://student.ugent.be/hydra/api/1.0/associations.json) uses `internalName`
* internal names of associations don't match, e.g. `FK` vs. `FKCENTRAAL`, or `GRAS` vs `JGroen`
* Sometimes `full_name` is used while `display_name` equals null, sometimes it's the reverse, and in other cases both are used in [associations.json](http://student.ugent.be/hydra/api/1.0/associations.json).

Tagging @mlumingu for a follow-up.

**Comment by Silox** [comment]
As the associations.json file is used in multiple applications
(FK-Enrolment, Gandalf) and perhaps also some FK-code, please notify
developers before changes are happening.

2015-12-07 23:10 GMT+01:00 Niels De Graef <notifications@github.com>:

**Comment by axd1967** [comment]
I think this is also related to our email "Zoneit/Hydra API [GH-0188]" dd
wo 1/04/2015 21:37 (michael lumingu, Michiel Van den Berghe; hydra; Tom
Naessens), right?

-alex-

**Comment by mlumingu** [comment]
- First issue is temporarily solved by also adding internal_name attribute to associations.json. This should not break anything for other apps using the api. @feliciaan will provide more details about how these two attributes will change in the future.

- Issue two was due to some inconsistencies in the dsa database and the api. This should be fixed now.


- Third issue:
Current structure of associations api:
if hydraDisplayName exists in dsatable
  displayName = hydraDisplayName
  fullName = fullName
else
  displayName = fullName
  fullName attribute is absent in api

I structured this api based on the example json file I was given.

**Comment by nielsdg** [comment]
Thanks for the quick reply. Will test as soon as possible!

**Comment by axd1967** [comment]
Can someone confirm what the impact of this API work will be for Zone-it?

**Comment by Silox** [comment]
@axd1967 The upgrade is backwards compatible, so there shouldn't be any impact for Zone-it.

**Comment by axd1967** [comment]
@Silox 

Just to clarify: an upgrade can be backward compatible, but in effect be "dead meat", in other words abandoned; the real "meat" is in the upgrade. Is this the case here? 

Have there been evolutions that Zone-it can benefit from? Because if that's the case, we had an agreement to discuss this *together*.

**Comment by Silox** [comment]
Hey Alex, I can’t know if there have been any evolutions that Zone-it can benefit from as I don’t know what is already included in Zone-it or how things are handled there. The changes are described in @mlumingu’s post, so you have to check out for yourself if these changes benifit Zone-it. 

Lastly, all discussions about the API have been taken in a public place (this topic) where you have replied to, and thus have been included in the conversation (which we will continue to do in the future).

The API is also still publicly available at http://student.ugent.be/hydra/api/ to anyone who wants to use it.
