### ISSUE TITLE
Update info for academic year 2017-18

### ISSUE THREAD

**Issue by feliciaan** [ZeusWPI/hydra#240]
Update the following files:
- [ ] info-fietsen
- [ ] info-kalender
- [ ] info-sport-aanbod
- [ ] info-sport-openingsuren
- [ ] info-studentenartsen

**Comment by niknetniko** [comment]
Since the official Ghent University websites are now responsive, I don't see much reason to continue maintaining (or not maintaining in the calendar case) these pages, as linking to the website is as good or even better:
- [The calendar](https://www.ugent.be/student/nl/studeren/kalender/kalender20172018.htm). We can link to the current year and update the link once a year.
- [Sport opening hours](https://www.ugent.be/student/nl/meer-dan-studeren/sport/openingsuren). Same content.
- [Sportaanbod](https://www.ugent.be/student/nl/meer-dan-studeren/sport/aanbod). The official site is almost identical to our HTML, but updated.
- [Studentenartsen](https://www.ugent.be/student/nl/meer-dan-studeren/gezondheid/studentenartsen.htm). This is also almost the same page, but updated.

Things we should update:
-  The page about bikes contains an overview of information that is not available in one place. We should however link the repair location to their website, so users can check if there are special hours, e.g. [`Kattenberg is gesloten vanaf maandag 02/04/2018 tot en met vrijdag 06/04/2018`](https://fietsambassade.gent.be/nl/contact/locaties/kattenberg).

Other stuff in `info-content.json`:
- The "Bloklocaties" should link directly to the Zeus blokmap instead of going through the HTML page first.
- Is the term GUIDe still used? The page now says 'FAQ', and I've only found the term in some older, obscure subpage of the site.
- Minerva Mobile should be just Minerva or be removed altogether.

This way, this removes a lot of maintenance work for us. Also, on Android, this is not a worse user experience, since the links (will) open in a Chrome Custom Tab.

**Comment by niknetniko** [comment]
If there are no objections, I'll do the things described above.

**Comment by wschella** [comment]
@niketniko, would it make sense to just render the page in a webview, or whatever the default is when you click links on android?

**Comment by wschella** [comment]
Excuse, you already mentioned Chrome custom tabs

**Comment by niknetniko** [comment]
Yup, the idea is to replace the four first item with a link to the official website (this is already supported, no app updates are necessary for this)

**Comment by niknetniko** [comment]
Fixed in #256.
